### ISSUE TITLE
Design para página das Receitas

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#10]
Fazer design para página:

https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas

**Comment by aimeesf** [comment]
primeiro teste

![gastos-abertos-graficos_desktop-teste-1](https://cloud.githubusercontent.com/assets/301256/6580990/cde4762e-c732-11e4-9782-86b80878fce5.png)
![gastos-abertos-graficos_mobile-teste-1](https://cloud.githubusercontent.com/assets/301256/6580991/cde4cf48-c732-11e4-9086-9fd743d9bdca.png)
