### ISSUE TITLE
Design da página raiz da Receita http://gastosabertos.org/receitas

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#100]
Design aprovado: https://drive.google.com/file/d/0BwlESUhjI_hiTDQ0ZWtGRVNDLWc/view
Textos: https://docs.google.com/document/d/1ZVRtRHgxOdsjOtKy5chlsp7zOwYgnDyjMdLf7YfEST0/edit

**Comment by LuizArmesto** [comment]
Fechando pois o design já está aprovado, falta implementação
