### ISSUE TITLE
Design da página raiz do Contratos http://gastosabertos.org/contratos

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#102]
Colocar aqui link para o design final.

**Comment by everton137** [comment]
Isso não tinha sido fechado, @sibigauer @aivuk ?

**Comment by sibigauer** [comment]
Mesma estrutura e UI da página receitas, intercalando as cores dos temas nos blocos. Necessidades específicas e assets sob demanda: 
https://drive.google.com/drive/u/0/folders/0BwlESUhjI_hiZ0FCOGtBWmg0VFE

**Comment by everton137** [comment]
Não faz mais sentido cair direto na ferramenta de navegação de contratos, @aivuk ? E a página aqui sugeri é uma página explicativo sobre os contrato que aparece num /sobre nalgum canto óbvio da página da ferramenta?

E se tivermos mais de um conjuntos de contratos (vi os do estado de SP, que talvez seja interessante usarmos num futuro não muito distante), como intercalar de forma inteligente?

Temos que pensar isso da mesma forma que vamos fazer com o caso das APIs.

**Comment by aivuk** [comment]
Não faz sentido pra mim, pois é melhor termos uma área que podemos ampliar depois, colocando destaques para novidades, eventos, novas ferramentas, etc relacionadas aos Contratos. Pense por exemplo se fizermo um evento de Crowdsourcing usando o Pybossa, ou se fizermos um tutorial explicando o uso da API dos Contratos, ou uma seção com projetos análogos. Se fizermos apontar direto pra Ferramenta, acabaremos recaindo no erro da página das Receitas, onde algumas pessoas cairam e não entenderam o contexto.

**Comment by everton137** [comment]
@aivuk eu acho que esse exempo que deu, de eventos e anúncios, deve ficar na página principal. Não faz sentido para mim ter um anúncio na página de contrato.

Eu acho que apontar direto para a ferramenta com um link ÓBVIO para explicação sobre ela resolve o problema.

**Comment by everton137** [comment]
Conversando com o @aivuk no Telegram, faz algum sentido o padrão das páginas /receita, /planejamento, /execução e /contratos

**Comment by sibigauer** [comment]
Ocorrências de outros pacotes de contratos que não o 2014 do mun. de São Paulo já estão previstos no design. Pensando bem, acho que vale eu incluir um layout para a landing com esses blocos, se eles irão parar lá. Amanhã incluo, pode ser? Igual, se quiserem dar uma olhada, tem as opções de boxes para "views" de contratos com 1/1 colunas, 1/3 colunas e 1/2 colunas nos layouts que coloquei na https://github.com/okfn-brasil/gastos_abertos_website/issues/97

**Comment by sibigauer** [comment]
@aivuk @LuizArmesto , precisam de assets específicos ou css para este desenvolvimento?
