### ISSUE TITLE
Mudar ordem dos posts da home

### ISSUE THREAD

**Issue by isisrf** [okfn-brasil/gastos_abertos_website#106]
Em vez de 'posts', acho que podemos colocar 'posts recentes' no título da seção e em vez de ser do primeiro post publicado para o mais recente, a ordem deve ser do mais recente para o mais antigo... Vocês não acham? Do jeito que está atualmente, não está fazendo muito sentido...

**Comment by everton137** [comment]
O @LuizArmesto já resolveu.

**Comment by everton137** [comment]
Resolução está aqui: 3d6eac45c3b250b37fbb4ba90b9b7aabd9a7f833
