### ISSUE TITLE
Artigo técnico: O que são APIs? Por que elas importam e como utilizá-las

### ISSUE THREAD

**Issue by everton137** [okfn-brasil/gastos_abertos_website#107]
A @isisrf começou um [artigo em português](https://docs.google.com/document/d/1D5arV2Xzj-y0faWdqHSKWBm0Npo1jctoP0TrzDL2QeU/edit#) traduzingo esse [artigo da Sunlight Foundation](https://sunlightfoundation.com/blog/2015/09/08/what-are-apis-why-they-matter-and-how-to-use-them/).

Precisamos apenas dar um bom exemplo usando nossas APIs.

**Comment by everton137** [comment]
@aivuk você faz ou acha que pode ficar com o @carlosandrade ?

**Comment by netojoaobatista** [comment]
Pessoal, posso ajudar com isso.

APIs entra muito na minha área de atuação e, em especial sobre comunicação
de APIs com desenvolvedores.

Em sex, 11 de dez de 2015 às 10:22, Tom notifications@github.com escreveu:

**Comment by everton137** [comment]
@netojoaobatista seria incrível se pudesse ajudar nisso. Aliás, hoje que horas posso te ligar? Depois do almoço funciona ou prefere mais para o fim da tarde?

**Comment by netojoaobatista** [comment]
@everton137, pode ser quando for mais apropriado para você.

:smile:

**Comment by everton137** [comment]
:+1:

**Comment by everton137** [comment]
@netojoaobatista para já ver nosso Swagger http://api.gastosabertos.org/

Queremos criar uma interface parecida com essa da Islândia para expandir para outras cidades: http://docs.apis.is/

O @carlosandrade começou algo nessa linha! https://gist.github.com/everton137/3893d1e45818a017e1fc

**Comment by aivuk** [comment]
@netojoaobatista  desconsidere o link que o @everton137 passou como exemplo de texto pra uso da API, esse documento é pra outra coisa e não é o exemplo de documentação que precisamos. Esse é mais um documento pra ajudar outros desenvolvedores a entenderem nosso projeto, nossa arquitetura e assim poderem nos ajudar.
