### ISSUE TITLE
Artigo técnico: Como estender nossas APIs para outras cidades?

### ISSUE THREAD

**Issue by everton137** [okfn-brasil/gastos_abertos_website#108]
O @carlosandrade começou [um artigo](https://gist.github.com/everton137/3893d1e45818a017e1fc). Estou colocando para o sprint da semana do dia 21.

É viável? (cc @carlosandrade @aivuk )

**Comment by aivuk** [comment]
Não seria um artigo, mas uma página que entraria em Contribua/Participe pra outros desenvolvedores. Parte das informações que o Carlos colocou no doc pra mim deverão estar no repositório do Github. Acho melhor quebrar essa tarefa em várias, vou olhar com mais cuidado e fazer isso, por enquanto deixo-a "em progresso" comigo.

**Comment by carlosandrade** [comment]
Concordo com o @aivuk, assim sendo esta tarefa não faz sentido ter deadline por agora. Principalmente quando o código ainda está bem "experimental". Como esclareci ao @everton137 hoje, o título disso é completamente misleading. Isso foi o que eu escrevi achando que a ideia era que seriamos um grande data hub para todas as cidades, o que o @aivuk deixou claro que não era o caso. Assim sendo, o que eu imagino ser mais perto de útil para esse documento é para acaso tenhamos algum novo voluntário interessado em contribuir com o código (como todo projeto Open Source costuma ter). 

O verdadeiro tutorial para outras cidades, seguindo a lógica do "Eu Voto" para ser multiplicador eu imagino que venha sair de uma discussão para um release 2.0 ou 3.0 e eu estou completamente por fora no momento. 

@aivuk você precisa conversar com o Tom em algum momento para elaborar melhor essas tarefas ou pelo menos definir o que vai para release 1.0 ou release 2.0, está começando a ficar confuso com os vários issues que o @everton137 está colocando no github. 

@everton137 sugiro pensar no que te falei: Preferência a coisas que caem na minha especialidade que é a parte de análise de dados, plots (preferencialmente estáticos) e R. Até agora só tem caido ou coisa com Python, website, ou código de crawler. Esses eu demoro mais e o custo/benefício seria melhor alocados para o @aivuk ou o @LuizArmesto. 

Esse negócio de **sprint** também não me está claro. Não eram só os milestones cujo primeiro é dia 18 de Janeiro? Também foi citado que eu entraria a partir de janeiro no pipeline a mais ou menos uma semana então estou ficando confuso. Até dia 21 eu já coloquei outras coisas como prioridades por conta do que foi decidido (e.g. tese de mestrado! :-) ).

**Comment by aivuk** [comment]
Carlos, tirei essa tarefa do Milestone 1.0, concordo contigo que da forma que está ela não faz sentido aqui. Quanto aos sprints, desconsidere-os, já expliquei ao @everton137 que não iremos utilizar os milestones para organizar os sprints.

**Comment by everton137** [comment]
Tirar do milestone não implicar que a tarefa não deve existir. Podemos fechar após quebrá-la, pode ser?

**Comment by aivuk** [comment]
Essa tarefa não é uma tarefa! Temos que analisar isso, deixar como tarefa só vai poluir pois isso não é uma tarefa aberta do website. Isso é uma tarefa que mais abrange o projeto, arquitetura dos nossos modelos de dados em outros repositórios, documentações, etc Deixei como inválido agora.
