### ISSUE TITLE
Design para gráfico de barras com drilldown

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#11]
https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas#gr%C3%A1fico-de-barra-com-drilldown

**Comment by aimeesf** [comment]
![gastos-abertos-graficos_barra](https://cloud.githubusercontent.com/assets/301256/6581003/e2bb3c7c-c732-11e4-9df7-a687830f122a.png)
