### ISSUE TITLE
Design para gráfico de série temporal

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#12]
https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas#gr%C3%A1fico-de-s%C3%A9rie-temporal

**Comment by aimeesf** [comment]
![gastos-abertos-graficos_linha](https://cloud.githubusercontent.com/assets/301256/6581017/eee9c900-c732-11e4-9d7f-70627a694fbc.png)
