### ISSUE TITLE
Design para tabela da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#13]
https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas#tabela-com-dados-da-receita-no-ano

Ver exemplo em:

http://demo.gastosabertos.org/receita/2014

**Comment by aimeesf** [comment]
![gastos-abertos-graficos_tabela](https://cloud.githubusercontent.com/assets/301256/6581010/e9d87ccc-c732-11e4-8d2c-9e7a35939edf.png)
