### ISSUE TITLE
Criar no Wiki lista de artigos a serem criados na área Blog do projeto

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#24]
Por enquanto as idéias são:
# Não aprofundado técnicamente
- Análise dos dados da Receita: a importância de APIs além de interfaces manuais.
- Entendo a localização nos dados do Planejamento.
# Aprofundado
- Arquitetura por trás do Projeto (API, Site Estático, Componenetes JS).
- Análise dos dados da Receita e construção de uma API.
- Análisde dos dados de Planejamento.

**Comment by everton137** [comment]
[Aqui](/okfn-brasil/gastos_abertos_website/wiki/Blog).

**Comment by LuizArmesto** [comment]
página wiki já feita
