### ISSUE TITLE
Tabela com dados da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#8]
Utilizando o Datatables:

https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas#tabela-com-dados-da-receita-no-ano

Paginado via ajax. Ver exemplo:

http://demo.gastosabertos.org/receita/2014

A busca não estará funcional já que não existe ainda um endpoint para buscas via texto.

Para esta tabela será utilizado o endpoint:

https://github.com/okfn-brasil/gastos_abertos/wiki/API#list-revenues

**Comment by LuizArmesto** [comment]
Subtarefas:
- [x] Renderizar a tabela com dados carregados via ajax
- [x] Exibir as datas e os valores monetários formatados
- [x] Sincronizar com o ano selecionado (a seleção de ano ainda não foi feita)
- [x] Paginação via ajax
  - [x] Receber do servidor o número total de registros (servidor ainda não envia)
  - [x] Fazer o meio de campo entre o formato que a API espera os parâmetros e o que o DataTables envia e entre o formato que a API enviará as info de paginação e o que o DataTables espera

https://datatables.net/manual/server-side
