### ISSUE TITLE
Página da Receita

### ISSUE THREAD

**Issue by aivuk** [okfn-brasil/gastos_abertos_website#9]
Descrição da página está em:

https://github.com/okfn-brasil/gastos_abertos_website/wiki/Receitas

E deverá possuir a visualizações descritas nas tarefas:
- Gráfico de barras com drilldown (#6)
- Gráfico de série temporal (#7)
- Tabela com dados da receita (#8)

Mas para fechar essa tarefa não é necessário fechar as tarefas acima.
Criar uma página da receita, conteúdo Markdown estará em:

pages/Receita.md

E o template html em:

templates/receita.html

Onde deverá estar definido as devidas importações de js necessários pra página. Mudanças das opções das visualizações deverão alterar o URL, via API de History/State do HTML5 (https://github.com/browserstate/history.js). A mesma coisa para mudanças nos ano ou nível da receita sendo observado.

Note que a mudança na opção do ano estará sincronizado nas três visualizações da página.

**Comment by LuizArmesto** [comment]
Aparentemente ainda não está sendo usado o markdown do arquivo "pages/Receita.md"

**Comment by andresmrm** [comment]
O conversor de Markdown, quando testei, não estava funcionando. Acho que até cheguei a mudar para outra biblioteca e dai foi.
Sobre usar Markdown na página da Receita, por enquanto não vejo muito motivo, já que não há muito texto lá... Talvez devamos usar MD só para as páginas que tenham mais conteúdo textual (e por enquanto parece que nenhuma tem, né?).
Eu votaria por fechar essa issue.
