### ISSUE TITLE
História do orçamento 1: execução de SIURB e SEHAB

### ISSUE THREAD

**Issue by everton137** [okfn-brasil/gastos_abertos_website#98]
Atualizado com comentários de SIURB e SEHAB em 18/12 _(Editado por Sérgio)_

Finalizado em:

https://docs.google.com/document/d/1lRSWogfC9VNsAoRuCMw1qBiklI5TX3ZBlcTEJXFaOsw/edit

**Comment by everton137** [comment]
Feito [aqui](https://docs.google.com/document/d/1lRSWogfC9VNsAoRuCMw1qBiklI5TX3ZBlcTEJXFaOsw/edit).

**Comment by sergiospagnuolo** [comment]
Necessita de revisão com dados atualizados do fechado de 2015

**Comment by sergiospagnuolo** [comment]
Resposta integral de SIURB e SEHAB: 

[Link aqui](https://docs.google.com/a/ok.org.br/document/d/1usZGptJ2eI2SVUmwaX03Vgk3NGUSnF3P6HL37fg9338/edit?usp=sharing)

**Comment by everton137** [comment]
@voltdatalab onde vejo a íntegra da sua solicitação?

**Comment by sergiospagnuolo** [comment]
Tá lá no Doc, você são muito rápidos, eu nem tinha acabado ainda!

—
Sérgio Spagnuolo

Jornalista - Gastos Abertos

sergio@ok.org.br

(11) 99651-1844

Twitter: @ProjetoStock

**Comment by everton137** [comment]
@voltdatalab foi coincidência de eu ver o aviso aqui, ler essa tarefa, ficar curioso e perguntar. :eyes:

**Comment by everton137** [comment]
O @voltdatalab vai atualizar os dados dessa história hoje (20 de jan).

**Comment by sergiospagnuolo** [comment]
@everton137 @aivuk os dados foram todos atualizados, creio que vocês dando o OK, podem publicar. Recomendo revisar os dados, eu mesmo revisei algumas vezes, mas possivelmente pode ter passado algo.

**Comment by everton137** [comment]
http://gastosabertos.org/historias/Atrasos_em_Obras_e_Repasses_Federais/
